# Generated by Django 4.0.3 on 2022-03-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cerrajero',
        ),
        migrations.DeleteModel(
            name='Futbolista',
        ),
    ]
